### ISSUE TITLE
how to run captcha_decoder.py ?

### ISSUE THREAD

**Issue by shashanksgowda** [bgeetika/Captcha-Decoder#2]
how to run your program. what are the arguments passed from command line?

**Comment by JEnIUS85** [comment]
hi,
I believe we have to specify following mandatory arguments..  But not sure if same value can be specified for "TrainingDirc",'ValidateDirc' and 'TestDirc'

TrainingDirc
ValidateDirc
TestDirc
ModelParamsFile
